app/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^profile/(\w+)', views.profile, name='profile'),
    url(r'^add/(?P<operation>.+)/(?P<name>\w+)', views.new_resident, name='new_being'),
    url(r'^area/(\w+)', views.residence, name='area'),
    url(r'^business/(\w+)', views.new_business, name='bizna'),
    url(r'^service/(\w+)', views.new_service, name='service'),
    url(r'^event/(\w+)', views.new_event, name='event'),
    url(r'^newhood$', views.new_hood, name='esto'),
    url(r'^search/', views.find_hood, name='search'),
    url(r'^change/(\w+)/', views.change, name='change'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

hood/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include ('app.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
]

app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Business(models.Model):
    business_name= models.CharField(max_length=50)
    email = models.EmailField()
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    neighbourhood = models.ForeignKey('app.Hood', on_delete=models.CASCADE, related_name='jirani')

    def __str__(self):
        return self.business_name

class Hood(models.Model):
    location_choices = (
        (1, 'Nairobi'),
        (2, 'Kajiado'),
        (3, 'Mombasa'),
        (4, 'Kilifi'),
        (5, 'Kiambu'),
    )
    name= models.CharField(max_length=50)
    location = models.IntegerField(choices=location_choices)
    occupants = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    @classmethod
    def get_hood(cls,jina):
        home = Hood.objects.filter(name__icontains=jina)
        return home

class Resident(models.Model):
    pic = models.ImageField(upload_to='images/')
    name = models.ForeignKey(User,on_delete=models.CASCADE)
    id_number = models.IntegerField(default=0)
    email=models.EmailField()
    home = models.ForeignKey(Hood, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.username

    @classmethod
    def get_human(cls,jina):
        human= Resident.objects.filter(name__username__icontains = jina)
        return human

    @classmethod
    def change_hood(cls, iden, hood):
        person = Resident.objects.filter(name__username__icontains = iden)
        person.update(home = hood)
        for object in person:
            object.save()
        return person

class Service(models.Model):
    area = models.ForeignKey(Hood, on_delete=models.CASCADE)
    type = models.CharField(max_length=50)
    name = models.CharField(max_length=50)
    contact = models.IntegerField(default=0)

    def __str__(self):
        return self.type

    @classmethod
    def get_service(cls,jina):
        service = Service.objects.filter(area__name__icontains= jina)
        return service

class Event(models.Model):
    affected = models.CharField(max_length=60)
    description= models.TextField()
    area = models.ForeignKey(Hood, on_delete=models.CASCADE)

    def __str__(self):
        return self.affected

    @classmethod
    def get_event(cls,jina):
        news = Event.objects.filter(area__name__icontains=jina)
        return news

app/forms.py
from django import forms
from .models import *

class NewResidentForm(forms.ModelForm):
    class Meta:
        model = Resident
        exclude = ['name', 'home']

class NewBusiness(forms.ModelForm):
    class Meta:
        model = Business
        exclude = ['owner', 'neighbourhood']

class NewService(forms.ModelForm):
    class Meta:
        model = Service
        exclude = ['area']

class NewEvent(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ['area']

class NewHoodForm(forms.ModelForm):
    class Meta:
        model = Hood
        exclude = ['occupants']

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *

# Create your views here.
@login_required(login_url='/accounts/login/')
def home(request):
    '''
    returns the homepage of the application
    '''
    residence = Hood.objects.all
    person = Resident.get_human(jina=request.user)
    return render(request, 'index.html', {'content': residence, 'eye':person})

@login_required(login_url='/accounts/login/')
def profile(request,name):
    human = Resident.get_human(jina=name)

    return render(request, 'profile.html', {'content': human})

@login_required(login_url='/accounts/login/')
def new_resident(request, operation, name):
    current_user = request.user
    hood = get_object_or_404(Hood, name=name)
    home = Hood.get_hood(jina=name)
    if request.method == 'POST':
        form = NewResidentForm(request.POST, request.FILES)
        if form.is_valid():
            resident = form.save(commit=False)
            resident.name = current_user
            resident.home = hood
            resident.save()
        return redirect('home')
    else:
        form = NewResidentForm()

    if operation == 'join':
        hood.occupants +=1
        hood.save()

    return render(request, 'new_being.html', {'form': form, 'content': home})

@login_required(login_url='/accounts/login/')
def residence(request,jina):
    area = Hood.get_hood(jina=jina)
    service = Service.get_service(jina=jina)
    news = Event.get_event(jina=jina)

    return render(request, 'area.html', {'content': area, 'addon': service, 'news':news})

@login_required(login_url='/accounts/login/')
def new_business(request,jina):
    current_user = request.user
    home = Hood.get_hood(jina=jina)
    area = get_object_or_404(Hood, name=jina)
    if request.method == 'POST':
        form = NewBusiness(request.POST, request.FILES)
        if form.is_valid():
            business = form.save(commit=False)
            business.owner = current_user
            business.neighbourhood = area
            business.save()

        return redirect('home')

    else:
        form = NewBusiness()

    return render(request, 'bizna.html', {'form': form, 'content': home})

@login_required(login_url='/accounts/login/')
def new_service(request,jina):
    home = Hood.get_hood(jina=jina)
    area = get_object_or_404(Hood, name=jina)
    if request.method == 'POST':
        form = NewService(request.POST, request.FILES)
        if form.is_valid():
            service = form.save(commit=False)
            service.area = area
            service.save()

        return redirect('home')

    else:
        form = NewService()

    return render(request, 'service.html', {'form': form, 'content': home})

@login_required(login_url='/accounts/login/')
def new_event(request,jina):
    home = Hood.get_hood(jina=jina)
    area = get_object_or_404(Hood, name=jina)
    if request.method == 'POST':
        form = NewEvent(request.POST, request.FILES)
        if form.is_valid():
            event = form.save(commit=False)
            event.area = area
            event.save()

        return redirect('home')

    else:
        form = NewEvent()

    return render(request, 'event.html', {'form': form, 'content': home})

@login_required(login_url='/accounts/login/')
def new_hood(request):
    if request.method == 'POST':
        form = NewHoodForm(request.POST, request.FILES)
        if form.is_valid():
            hood = form.save(commit=False)
            hood.save()

        return redirect('home')

    else:
        form = NewHoodForm()

    return render(request, 'pop.html', {'form': form})

@login_required(login_url='/accounts/login/')
def find_hood(request):
    if 'hood' in request.GET and request.GET['hood']:
        jina = request.GET.get('hood')
        hood = Hood.get_hood(jina=jina)

        return render(request, 'search.html', {'title': jina, 'content': hood})

    else:
        return render(request, 'search.html')

@login_required(login_url='/accounts/login/')
def change(request,name):
    if 'home' in request.GET and request.GET['home']:
        place = request.GET.get('home')
        new = Resident.change_hood(iden= name, hood=place)
        print(new)

        return redirect('home')

    else:
        return render(request, 'gum.html')

app/templates/area.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
  <div class="col-md-4 col-sm-4 col-lg-4">
    {% for con in content %}
    <div class="card" style="margin-top:150px; background-color:#55d6ed;">
      <div class="card-header">
        <h4 style="text-align:center;">
          <b>Residence: {{con.name}}</b>
        </h4>
      </div>
      <div class="card-body">
        <p>
          <b>Location:</b> {{con.get_location_display}} county
        </p>
        <p>
          <b>Population:</b> {{con.occupants}}
        </p>
        <a href="/business/{{con.name}}" class="btn btn-md btn-info">Add Business</a><br>
        <a href="/service/{{con.name}}" class="btn btn-md" style="background-color:#66ff33;">Add Service</a>
        <a href="/event/{{con.name}}" class="btn btn-md btn-danger">Add Incident</a>
      </div>
    </div><br>
    {% endfor %}
    {% if news %}
    {% for new in news %}
    <div class="card">
      <div class="card-body">
        <h4>
          <b>Household:</b> {{new.affected}}
        </h4>
        <p>
          <b>Description:</b> {{new.description}}
        </p>
      </div>
    </div><br>
    {% endfor %}
    {% else %}
    <h4 style="color:red">
      <b>No Incidents</b>
    </h4>
    {% endif %}
  </div>
  <div class="col-md-4 col-sm-4 col-lg-4">
    <h3 style="color:#66ff33;">
      <b>Businesses</b>
    </h3>
    {% for con in content %}
    {% if con.jirani.all %}
      {% for item in con.jirani.all %}
        <div class="card">
          <div class="card-body">
            <h5>
              <b>Name:</b> {{item.business_name}}
            </h5>
            <p>
              <b>Owner:</b> {{item.owner}}
            </p>
            <p>
              <b>Email</b> {{item.email}}
            </p>
          </div>
        </div><br>
      {% endfor %}
    {% else %}
    <h4 style="text-align:center;">
      <b>No businesses yet click the button to be the first</b>
    </h4>
    <a href="#" class="btn btn-md btn-info">Add</a>
    {% endif %}
    {% endfor %}
  </div>
  <div class="col-md-4 col-sm-4 col-lg-4">
    <h3 style="color:#55d6ed;">
      <b>Services</b>
    </h3>
    {% if addon %}
    {% for add in addon %}
    <div class="card">
      <div class="card-body">
        <h4>
          <b>Type:</b> {{add.type}}
        </h4>
        <p>
          <b>Name:</b> {{add.name}}
        </p>
        <p>
          <b>Contact:</b> {{add.contact}}
        </p>
      </div>
    </div><br>
    {% endfor %}
    {% else %}
    <h4 style="color:red;">No registered services yet</h4>
    {% endif %}
  </div>
</div>
{% endblock %}

app/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% if title %}
      <title>{{title}}</title>
    {% else %}
      <title>Hood Watch</title>
    {% endif %}

    {% block styles %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    {% endblock %}
  </head>
  <body>

    {% include 'navbar.html' %}

    {% block content %}

    {% endblock %}

    {% block scripts %}
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
      </script>
    {% bootstrap_javascript %}
    {% endblock %}

  </body>
</html>

app/templates/bizna.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Project</title>
    {{form.media}}
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
  </head>
  <body>
    {% for con in content %}
    <form  action="/business/{{con.name}}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-md" value="Add">
  </form>
  {% endfor %}
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
  </body>
</html>

app/templates/event.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Project</title>
    {{form.media}}
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
  </head>
  <body>
    {% for con in content %}
    <form  action="/event/{{con.name}}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-md" value="Add">
  </form>
  {% endfor %}
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
  </body>
</html>

app/templates/gum.html
{% extends 'base.html' %}
{% block content %}


<form class="form-inline my-2 my-lg-0" action="/change/{{user.username}}" method="get">
<input type="search" name="home" placeholder="New Residence" aria-label="Search" class="form-control container-fluid">
<button type="submit" class="btn" style="border-radius:8px; background-color:#55d6ed;">Save Changes</button>
</form>



{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="d-flex justify-content-center" style="margin-top:10px;">
    <a href="/newhood" class="btn btn-md" style="background-color:#55d6ed;">Add Residence</a>
  </div>
  {% if eye %}
  <div class="row" style="margin-top:10px;">
    {% for con in content %}
    <div class="card" style="background-color:#87e598;width:48%; margin-bottom: 10px; margin-right:5px;">
      <div class="card-body">
        <h4>
          <b>Residence: {{con.name}}</b>
        </h4>
        <p>
          <b>Location:</b>{{con.get_location_display}}
        </p>
        <p>
          <b>Population:</b>{{con.occupants}}
        </p>
      </div>
      <div class="card-footer">
        {% for i in eye %}
        <a href="/change/{{i.name.username}}/?home={{con.id}}" class="btn btn-md" style="background-color: #66ff33;">Change to this Residence</a>
        {% endfor %}
        </div>
      </div>
      {% endfor %}
    </div>

  {% else %}
  <div class="row" style="margin-top:10px;">
    {% for con in content %}
    <div class="card" style="background-color:#87e598;width:48%; margin-bottom: 10px; margin-right:5px;">
      <div class="card-body">
        <h4>
          <b>Residence: {{con.name}}</b>
        </h4>
        <p>
          <b>Location:</b>{{con.get_location_display}}
        </p>
        <p>
          <b>Population:</b>{{con.occupants}}
        </p>
      </div>
      <div class="card-footer">
        <a href="{% url 'new_being' operation='join' name=con.name %}" id="join" class="btn btn-md btn-info">Join</a>
        </div>
      </div>
      {% endfor %}
    </div>
  {% endif %}


    </div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-light bg-light" style="background: linear-gradient(to right, #55d6ed 20%, #66ff33 100%);">
  <a href="{% url 'home' %}" class="navbar-brand">DansHood</a>
  <div class="col-md-6 col-sm-6">
    {% if user.is_authenticated %}
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a href="{% url 'home'%}" class="nav-link">Residences</a>
      </li>
      <li class="nav-item">
        <a href="/profile/{{user.username}}" class="nav-link">Personal Info</a>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="dropdown-toggle btn btn-default nav-link" data-toggle="dropdown" role="button" aria-expanded="false">Account</a>
        <ul class="dropdown-menu" role="menu">
          <li></li>
          <li>
          <a href="/accounts/password/change">Change Password</a>
        </li>
        <li>
          <a href="/logout">Logout</a>
        </li>
      </ul>
    </li>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search' %}" method="get">
    <input type="search" name="hood" placeholder="Search Residence" aria-label="Search" class="form-control container-fluid">
    <button type="submit" class="btn" style="border-radius:8px; background-color:#55d6ed;">Search</button>
  </form>
  </ul>
  {% else %}
  <li>
    <a class='btn btn-default' href="/accounts/login">Login</a>
  </li>

  {% endif %}

  </div>

</nav>

app/templates/new_being.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Project</title>
    {{form.media}}
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
  </head>
  <body>
    {% for con in content %}
    <form  action="{%url 'new_being' operation='join' name=con.name %}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-md" value="edit">
  </form>
  {% endfor %}
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
  </body>
</html>

app/templates/pop.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Project</title>
    {{form.media}}
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
  </head>
  <body>

    <form  action="/newhood" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-md" value="Add">
  </form>
  
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
  </body>
</html>

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  {% if content %}
    <h4 style="text-align:center;">
      <b style="color:blue;">Visible to you alone</b>
    </h4>
    {% for con in content %}
    <div class="card" style="margin-left:10%; margin-right: 10%; border:hidden;">
      <img class="img-fluid card-img-top" src="{{con.pic.url}}" alt="">
      <div class="card-body">
        <p>
          <b>Name:</b> {{con.name.username}}
        </p>
        <p>
          <b>Email:</b> {{con.email}}
        </p>
        <p>
          <b>Residence:</b> {{con.home.name}}
        </p>
      </div>
      <div class="card-footer" style="background-color:white;">
        <div class="row">
          <div class="col-md-5 col-sm-5 col-lg-5"></div>
          <div class="col-md-2 col-sm-2 col-lg-2">
            <a href="/area/{{con.home.name}}" class="btn btn-md btn-info">Residence Detais</a>
          </div>
          <div class="col-md-5 col-sm-5 col-lg-5"></div>
        </div>
      </div>
    </div>
    {% endfor %}
  {% else %}
  <h4>
    <b>Please click the button to join residence and continue</b>
  </h4>
  <div class="row">
    <div class="col-md-5 col-sm-5 col-lg-5"></div>
    <div class="col-md-2 col-sm-2 col-lg-2">
      <a href="{% url 'home' %}" class="btn btn-md btn-info">New Info</a>
    </div>
    <div class="col-md-5 col-sm-5 col-lg-5"></div>
  </div>
  {% endif %}
</div>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}
{% block content %}
{% if content%}

{% for con in content %}
<div class="card" style="background-color:#87e598;width:50%; margin-bottom: 10px; margin-right:5px;">
  <div class="card-body">
    <h4>
      <b>Residence: {{con.name}}</b>
    </h4>
    <p>
      <b>Location:</b>{{con.get_location_display}}
    </p>
    <p>
      <b>Population:</b>{{con.occupants}}
    </p>
  </div>
  <div class="card-footer">
    <a href="{% url 'new_being' operation='join' name=con.name %}" id="join" class="btn btn-md btn-info">Join</a>
    </div>
  </div>
  {% endfor %}
{% else %}
<h3 style="text-align:center;">
  <b>No Items match your input. Click button to add it</b>
</h3>
<div class="d-flex justify-content-center" style="margin-top:10px;">
  <a href="/newhood" class="btn btn-md" style="background-color:#55d6ed;">Add Residence</a>
</div>
{% endif %}
{% endblock %}

app/templates/service.html
{% load bootstrap4 %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>New Project</title>
    {{form.media}}
    {% block styles %}
    {% bootstrap_css %}
    {% endblock %}
  </head>
  <body>
    {% for con in content %}
    <form  action="/service/{{con.name}}" method="post" enctype="multipart/form-data">
    {%csrf_token%}

    {% bootstrap_form form%}
    <input type="submit" class="btn btn-primary btn-md" value="Add">
  </form>
  {% endfor %}
   {% block scripts %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  {% bootstrap_javascript %}
  {% endblock %}
  </body>
</html>